config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resource :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  get :search, controller: :users
  resources :requests, only: %i[create destroy index] do
    member do
      post :edit
    end
  end
  resources :users do
    resources :stories, only: %i[create destroy new index show]
  end
  resources :posts do
    resources :comments
  end
  resources :home, only: %i[index]
  authenticated do
    root 'users#index'
  end

  unauthenticated do
    root 'home#index'
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_post, only: %i[create show edit update destroy]
  before_action :set_comment, only: %i[show edit update destroy]
  after_action :verify_authorized

  def show; end

  def edit; end

  def new
    @comment = Comment.new
    authorize @comment
  end

  def create
    @comment = @post.comments.new(comment_params)
    authorize @post
    if @comment.save
      render 'create', flash: { notice: 'Comment Added!' }
    else
      redirect_to post_url(@post), notice: @comment.errors.full_messages.to_sentence.to_s

    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @post, notice: 'Comment was successfully updated. '
    else
      redirect_to edit_post_comment_url, notice: @comment.errors.full_messages.to_sentence.to_s
    end
  end

  def destroy
    if @comment.destroy
      redirect_to @post, notice: 'Comment was successfully deleted.'
    else
      redirect_to comments_url, notice: @comment.errors.full_messages.to_sentence.to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id, [:comment])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end
end

app/views/comments/_comment.html.erb
<div class="comment_container">
  <% @user = User.find(comment.user_id) %>
  <% @post = Post.find(comment.post_id)%>
  <%= image_tag select_avatar(@user), class:"img-circle img-thumbnail user_image"%>
  <span class="username"><%= @user.username %> : </span>
  <%= comment.content %>
  <% if current_user == @user%>
    <%= link_to image_tag('edit.png',class:"icon_comment"), edit_post_comment_path(@post.id, comment.id) if policy(comment).update? %>
  <% end %>
  <%= link_to image_tag('delete.png',class:"icon_comment"), post_comment_path(@post.id,comment.id), method: :delete, data: { confirm: 'Are you sure?' } if policy(comment).destroy?%>
</div>

app/views/comments/_errors.html.erb
<div class="alert alert-danger" role="alert">
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/comments/_form.html.erb
<% @comment = @post.comments.build%>
<%= form_with model: [ @post, @comment ] do |form| %>
  <% if @comment.errors.any? %>
    <%= render 'comments/errors', locals: {post: @comment} %>
  <% end %>
  <div class="form-group">
    <%= form.text_field :content, class:"form-control", placeholder:"Comment", required: true %>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id,id: :comment_user_id,class:"form-control",value: current_user.id, type: :hidden %>
  </div>

  <div class="field form-group">
    <%= form.number_field :post_id,id: :comment_post_id,class:"form-control",value: @post.id, type: :hidden %>
  </div>
  <div class="btn btn-defaults">
    <button type="submit" class="btn btn-default">Comment</button>
  </div>
  <% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");

app/views/comments/edit.html.erb
<div class="container">
  <%= form_with model: [@post, @comment], validate: true do |form| %>
    <% if @comment.errors.any? %>
      <%= render 'comments/errors', locals: {post: @comment} %>
    <% end %>
    <p>
      <%= form.text_area :content,class:"form-control" %>
    </p>
    <p class="actions">
      <%= form.submit class:"btn btn-secondary" %>
    </p>

    <div class="field form-group">
      <%= form.number_field :user_id,id: :comment_user_id,class:"form-control",value: @comment.user_id, type: :hidden %>
    </div>

    <div class="field form-group">
      <%= form.number_field :post_id,id: :comment_post_id,class:"form-control",value: @post.id, type: :hidden %>
    </div>

  <% end %>
</div>