config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resource :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  get :search, controller: :users
  resources :requests, only: %i[create destroy index] do
    member do
      post :edit
    end
  end
  resources :users do
    resources :stories, only: %i[create destroy new index show]
  end
  resources :posts do
    resources :comments
  end
  resources :home, only: %i[index]
  authenticated do
    root 'users#index'
  end

  unauthenticated do
    root 'home#index'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one_attached :avatar
  has_many :posts, dependent: :destroy
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Relationship', dependent: :destroy,
                            inverse_of: :follower
  has_many :followee, through: :followed_users, source: :followee
  has_many :following_users, foreign_key: :followee_id, class_name: 'Relationship', dependent: :destroy,
                             inverse_of: :followee
  has_many :followers, through: :following_users, source: :follower
  has_many :recieved_requests, class_name: 'Request', foreign_key: :reciever_id, dependent: :destroy,
                               inverse_of: :reciever
  has_many :sent_requests, class_name: 'Request', foreign_key: :sender_id, dependent: :destroy, inverse_of: :sender
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :stories, dependent: :destroy

  validates :username, :full_name, :privacy, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  scope :name_search, ->(name) { where('username ILIKE ?', "%#{name}%") }

  def following?(user)
    followee.include?(user)
  end

  def accept_request(user)
    ActiveRecord::Base.transaction do
      if following_users.create!(follower_id: user.id)
        user.sent_requests.find_by(reciever_id: id).destroy!
        return true
      end
    end
  rescue ActiveRecord::RecordInvalid
    errors[:base] << user.errors.to_s
  end

  def delete_request(user)
    return true if sent_requests.find_by(reciever_id: user.id).destroy

    errors[:base] << 'Request not deleted successfully'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  after_action :verify_authorized

  def index
    @users = User.all
    authorize @users
  end

  def show; end

  def search
    @users = User.name_search(params[:q])
    authorize @users
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def back_rout(user)
    return users_path if user != current_user

    posts_path
  end

  def select_avatar(user)
    return user.avatar if user.avatar.attached?

    'user.png'
  end
end

app/views/users/_feed.html.erb
<% @posts = Post.all%>
<% @posts.each do |post|%>
  <% @user =User.find(post.user_id) %>
  <% if @user!=current_user%>
    <% if current_user.following?(@user)%>
      <div class="panel panel-danger">
        <div class="panel-heading"style="background-color:#f5dff2">
          <%= image_tag select_avatar(@user), class:"img-circle img-thumbnail user_image"%>
          <%= @user.username%>
        </div>
        <div class="panel-body">
          <div class="row center-block">
            <% if post.images.attached?%>
              <%= link_to image_tag(post.images.first, class:"feed_image img-rounded"), post, class:"link" %>
            <% end %>
            <% @post = post%>
            <%= render 'likes/like', locals: {post: @post} %>
            <%= link_to image_tag('comment.png',class:"icon"), post %>
            <br>
          </div>
          <p class="caption"><%= post.caption %></p>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/_showpage.html.erb
<div class="row center-block" style="width:1000px">
        <div class="col-md-3 col-md-offset-2">
            <%= image_tag select_avatar(@user), :width=>200, :height=>300, :crop=>"fill", class:"img-circle img-thumbnail"%>
        </div>
        <div class="col-md-3 col-md-offset-2">
            <h3><%= @user.username%></h3>
            <h4><%= @user.full_name%></h4>
            <h5><%= @user.bio%></h5>
            <% if current_user.following?(@user) %>
                <% if policy(@user).user_exist?%>
                    <h5><%= button_to "Unfollow", relationships_path(user_id: @user.id), method: :delete, :class => "btn btn default" %></h5>
                <%end%>
            <% elsif requested?(current_user.sent_requests,@user)  %>
                Requested
            <% else %>
                <% if @user.privacy ==  'Public'%>
                    <% if policy(@user).user_exist? %>
                        <h5><%= button_to "Follow", relationships_path(user_id: @user.id), :class => "btn btn default" %></h5>
                    <% end %>
                <% else %>
                    <% if policy(@user).user_exist? %>
                        <h5><%= button_to "Follow", requests_path(reciever_id: @user.id), method: :post, :class => "btn btn default" %></h5>
                    <% end %>
                <% end%>
            <% end %>
        </div>
    </div>

app/views/users/index.html.erb
<div class="container">
  <div class="feed">
    <% @stories = Story.all%>
    <% @users = User.all%>
    <% @users.each do |user|%>
      <% if current_user.following?(user) || user == current_user%>
        <% if user.stories.any?%>
          <%= link_to image_tag(select_avatar(user), :crop=>"fill",  class:"img-circle img-thumbnail stories_img"), user_stories_path(user_id: user.id ) %>
        <% end %>
      <% end %>
    <% end %>
    <% if !current_user.followee.any? %>
      <div class="panel panel-danger">
        <div class="panel-body no_follow">
          Follow users to view their posts
        </div>
      </div>
    <% else %>
      <%= render 'feed' %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<div class="container">
  <h2>Search results</h2>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Full Name</th>
        <th>User Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.full_name, user_path(user.id) %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
    <%= render 'showpage',locals: {user: @user} %>
    <br/>
    <% if current_user.following?(@user) || @user.privacy == "Public"%>
        <div class="panel panel-danger">
            <div class="panel-heading text-center"style="background-color:#f5dff2">Posts</div>
            <div class="panel-body">
                <div class="row center-block">
                    <div class="col">
                        <% @user.posts.each do |post| %>
                            <% if post.images.attached?%>
                                <%= link_to image_tag(post.images.first, width:"350", height:"350", class:"img-rounded", :style=>'border:1px solid black; margin:5px'), post, class:"link" %>
                            <% end %>
                        <% end %>
                    </div>
                <div>
            </div>
        </div>
    <% end %>
</div>