config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resource :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  get :search, controller: :users
  resources :requests, only: %i[create destroy index] do
    member do
      post :edit
    end
  end
  resources :users do
    resources :stories, only: %i[create destroy new index show]
  end
  resources :posts do
    resources :comments
  end
  resources :home, only: %i[index]
  authenticated do
    root 'users#index'
  end

  unauthenticated do
    root 'home#index'
  end
end

app/models/story.rb
# frozen_string_literal: true

class Story < ApplicationRecord
  after_save :delete_story

  belongs_to :user
  has_many_attached :images, dependent: :destroy

  validates :images, presence: true
  validate :correct_image_type

  scope :user_stories, ->(id) { where(user_id: id) }

  private

  def delete_story
    DeleteStoriesJob.set(wait: 1.day).perform_later(id)
  end

  def correct_image_type
    return unless images.attached?

    images.each do |image|
      unless image.content_type.in?(%w[image/jpeg image/png image/gif image/jpg])
        errors[:base] << 'You tried uploading which is not jpeg/jpg/png/gif'
      end
    end
  end
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

class StoriesController < ApplicationController
  before_action :set_story, only: %i[show destroy]
  before_action :set_user, only: %i[index new show destroy create]
  # after_action :verify_authorized
  before_action :check_user, only: [:new]

  def index
    @stories = Story.all
    @json_stories = @stories.map { |e| e.as_json.merge(images: e.images.map { |image| url_for(image) }) }
    render json: {all_data:{json_stories: @json_stories}}
    # authorize @stories
  end

  def new
    @story = Story.new
    # authorize @story
  end

  def show; end

  def create
    @story = @user.stories.new(story_params)
    # authorize @story
    if @story.save
      redirect_to users_url, notice: 'story is successfuly created'
    else
      redirect_to new_user_story_url, notice: @story.errors.full_messages.to_sentence.to_s
    end
  end

  def destroy
    if @story.destroy
      redirect_to users_url, notice: 'Story was successfully deleted.'
    else
      redirect_to users_url, notice: "Something went wrong. #{@story.errors.full_messages.to_sentence}"
    end
  end

  private

  def story_params
    params.require(:story).permit(:user_id, images: [])
  end

  def set_story
    @story = Story.find(params[:id])
    # authorize @story
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def check_user
    set_user
    return true if @user.eql? current_user

    redirect_to users_path, notice: 'You are not authorized to perform this action'
  end
end

app/views/stories/index.html.erb
<div class="container">
  <div class="panel panel-danger">
    <div class="panel-body">
    <% @user = User.find(params[:user_id])%>
      <div class="row">
        <% @user.stories.each do |story|%>
          <div class="col-md-7">
            <% if story.images.attached? %>
              <% story.images.each do |image|%>
                <%= link_to image_tag(image ,class:"post_image_l border border-start"), user_story_path(user_id: @user.id, id: story.id)%>
              <%end%>
            <%end%>
          </div>
          <% @user = User.find(story.user_id)%>
        <% end %>
        <div class="col-md-5">
          <div class="fs-4 mt-3">
            <%= image_tag select_avatar(@user), :crop=>"fill", class:"img-circle img-thumbnail user_image"%>
            <%= @user.username%>
          </div>
        </div>
    </div>
    <%= link_to 'Back', users_path, class:"btn btn-default mt-3" %>
  </div>
</div>

app/views/stories/new.html.erb
<div class="container">
  <% @story = @user.stories.build%>
  <%= form_with model:[@user, @story] do |form| %>
    <% if @story.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div id="error_explanation">
          <h2><%= pluralize(@story.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @story.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.file_field :images, class:"form-control", type:"file", id:"formFile", multiple: true, direct_upload: true, accept: 'image/*', required: true%>
    </div>
    <div class="form-group">
      <%= form.number_field :user_id, id: :story_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    </div>
    <div class="btn btn-defaults">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  <% end %>
</div>

app/views/stories/show.html.erb
<div class="container">
  <div class="panel panel-danger">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-7">
          <% if @story.images.attached? %>
            <% @story.images.each do |image|%>
              <%= image_tag image ,class:"post_image_l border border-start"%>
            <%end%>
          <%end%>
        </div>
        <% @user = User.find(@story.user_id)%>
        <div class="col-md-5">
          <div class="fs-4 mt-3">
            <%= image_tag select_avatar(@user), :crop=>"fill", class:"img-circle img-thumbnail user_image"%>
            <%= @user.username%>
          </div>
          <%= link_to image_tag('delete.png',class:"icon_comment"), user_story_path(@user.id, @story.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"destroy" if policy(@story).destroy?%>
        </div>
    </div>
    <%= link_to 'Back', user_stories_path , class:"btn btn-default mt-3" %>
  </div>
</div>