config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resource :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  get :search, controller: :users
  resources :requests, only: %i[create destroy index] do
    member do
      post :edit
    end
  end
  resources :users do
    resources :stories, only: %i[create destroy new index show]
  end
  resources :posts do
    resources :comments
  end
  resources :home, only: %i[index]
  authenticated do
    root 'users#index'
  end

  unauthenticated do
    root 'home#index'
  end
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default"style="background-color:#f5dff2">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#">
        <%= image_tag ('instaa.png'), :class=> "nav_brand"%>
      </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in?%>
            <li>
              <%= link_to 'Feed', users_path, class: "nav_links" if policy(current_user).user_exist?%>
            </li>
            <li class="nav-item">
              <%= link_to 'Create story', new_user_story_path(user_id: current_user.id), class: "nav_links" if policy(current_user).user_exist? %>
            </li>
            <li class="nav-item">
              <%= link_to 'Requests', requests_path, class: "nav_links" if policy(current_user).user_exist? %>
            </li>
            <li>
              <%=link_to image_tag(select_avatar(current_user), :crop=>"fill",  class:"img-circle img-thumbnail user_image"), posts_path%>
            </li>
            <li>
              <%if user_signed_in?%>
                <form class="form-inline my-2 my-lg-0" action="/search">
                  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search", required="required">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              <%end%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav_links" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav_links" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if notice%>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
  </body>
</html>